import jsPDF from 'jspdf'
import { calculatePlateCost, calculateSuggestedPrice, calculateFoodCostPercentage } from './calculations'
import { calculateIngredientCost } from './unitConversions'

/**
 * Export dish to PDF
 */
export const exportDishToPDF = (dish) => {
  const plateCost = calculatePlateCost(dish.ingredients || [])
  const suggestedPrice = calculateSuggestedPrice(plateCost, dish.target_margin || 30)
  const sellingPrice = dish.selling_price || suggestedPrice
  const foodCostPercentage = calculateFoodCostPercentage(plateCost, sellingPrice)
  const grossProfit = sellingPrice - plateCost

  // Create new PDF document
  const doc = new jsPDF()
  
  // Set font
  doc.setFont('helvetica', 'bold')
  
  // Title
  doc.setFontSize(20)
  doc.setTextColor(139, 92, 246) // Purple
  doc.text(dish.name, 20, 20)
  
  // Reset font
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0) // Black
  
  let yPos = 35
  
  // Summary section
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('Cost Summary', 20, yPos)
  yPos += 10
  
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  
  doc.text(`Plate Cost: $${plateCost.toFixed(2)}`, 25, yPos)
  yPos += 7
  
  if (sellingPrice > 0) {
    doc.text(`Selling Price: $${sellingPrice.toFixed(2)}`, 25, yPos)
    yPos += 7
    doc.text(`Food Cost: ${foodCostPercentage.toFixed(1)}%`, 25, yPos)
    yPos += 7
    doc.text(`Gross Profit: $${grossProfit.toFixed(2)}`, 25, yPos)
    yPos += 7
    doc.text(`Target Margin: ${dish.target_margin || 30}%`, 25, yPos)
  } else {
    doc.text(`Suggested Price: $${suggestedPrice.toFixed(2)}`, 25, yPos)
    yPos += 7
    doc.text(`Target Margin: ${dish.target_margin || 30}%`, 25, yPos)
  }
  
  yPos += 10
  
  // Ingredients section
  if (dish.ingredients && dish.ingredients.length > 0) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.text('Ingredients', 20, yPos)
    yPos += 10
    
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    
    // Table header
    doc.setFont('helvetica', 'bold')
    doc.text('Name', 20, yPos)
    doc.text('Quantity', 80, yPos)
    doc.text('Unit Cost', 120, yPos)
    doc.text('Total Cost', 160, yPos)
    yPos += 7
    
    // Table rows
    doc.setFont('helvetica', 'normal')
    dish.ingredients.forEach((ingredient, index) => {
      // Check if we need a new page
      if (yPos > 250) {
        doc.addPage()
        yPos = 20
      }
      
      const quantity = ingredient.quantity || 0
      let unitCost = 0
      
      // Calculate unit cost based on costing mode
      if (ingredient.package_cost && ingredient.package_size && ingredient.package_unit) {
        // Package-based costing
        unitCost = calculateIngredientCost(
          parseFloat(ingredient.package_cost),
          parseFloat(ingredient.package_size),
          ingredient.package_unit,
          parseFloat(ingredient.quantity || 0),
          ingredient.unit || 'g'
        )
      } else {
        // Individual-based costing
        unitCost = parseFloat(ingredient.unit_cost || 0) * parseFloat(quantity)
      }
      
      // Truncate long names
      const name = ingredient.name.length > 25 
        ? ingredient.name.substring(0, 22) + '...' 
        : ingredient.name
      
      doc.text(name, 20, yPos)
      doc.text(`${quantity} ${ingredient.unit || 'g'}`, 80, yPos)
      doc.text(`$${(unitCost / quantity).toFixed(4)}`, 120, yPos)
      doc.text(`$${unitCost.toFixed(2)}`, 160, yPos)
      
      yPos += 7
    })
  }
  
  // Footer
  const pageCount = doc.internal.pages.length - 1
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(128, 128, 128)
    doc.text(
      `Generated by PlateWise - Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    )
    doc.text(
      new Date().toLocaleDateString(),
      105,
      doc.internal.pageSize.height - 5,
      { align: 'center' }
    )
  }
  
  // Save PDF
  const fileName = `${dish.name.replace(/[^a-z0-9]/gi, '_')}_costing.pdf`
  doc.save(fileName)
}

/**
 * Export dish to CSV
 */
export const exportDishToCSV = (dish) => {
  const plateCost = calculatePlateCost(dish.ingredients || [])
  const suggestedPrice = calculateSuggestedPrice(plateCost, dish.target_margin || 30)
  const sellingPrice = dish.selling_price || suggestedPrice
  const foodCostPercentage = calculateFoodCostPercentage(plateCost, sellingPrice)
  const grossProfit = sellingPrice - plateCost

  // Build CSV content
  let csv = `Dish: ${dish.name}\n`
  csv += `Generated: ${new Date().toLocaleString()}\n\n`
  
  // Summary section
  csv += `Cost Summary\n`
  csv += `Plate Cost,$${plateCost.toFixed(2)}\n`
  if (sellingPrice > 0) {
    csv += `Selling Price,$${sellingPrice.toFixed(2)}\n`
    csv += `Food Cost,${foodCostPercentage.toFixed(1)}%\n`
    csv += `Gross Profit,$${grossProfit.toFixed(2)}\n`
  } else {
    csv += `Suggested Price,$${suggestedPrice.toFixed(2)}\n`
  }
  csv += `Target Margin,${dish.target_margin || 30}%\n\n`
  
  // Ingredients section
  if (dish.ingredients && dish.ingredients.length > 0) {
    csv += `Ingredients\n`
    csv += `Name,Quantity,Unit,Unit Cost,Total Cost\n`
    
    dish.ingredients.forEach((ingredient) => {
      const quantity = ingredient.quantity || 0
      let unitCost = 0
      
      // Calculate unit cost based on costing mode
      if (ingredient.package_cost && ingredient.package_size && ingredient.package_unit) {
        // Package-based costing
        unitCost = calculateIngredientCost(
          parseFloat(ingredient.package_cost),
          parseFloat(ingredient.package_size),
          ingredient.package_unit,
          parseFloat(ingredient.quantity || 0),
          ingredient.unit || 'g'
        )
      } else {
        // Individual-based costing
        unitCost = parseFloat(ingredient.unit_cost || 0) * parseFloat(quantity)
      }
      
      const unitCostPerUnit = quantity > 0 ? unitCost / quantity : 0
      
      // Escape commas in name
      const name = `"${ingredient.name.replace(/"/g, '""')}"`
      
      csv += `${name},${quantity},${ingredient.unit || 'g'},$${unitCostPerUnit.toFixed(4)},$${unitCost.toFixed(2)}\n`
    })
  }
  
  // Create blob and download
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)
  link.setAttribute('href', url)
  link.setAttribute('download', `${dish.name.replace(/[^a-z0-9]/gi, '_')}_costing.csv`)
  link.style.visibility = 'hidden'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}


